// Writes every flat copy of the red panda's head from the shapes in
// web/src/components/redPandaShapes.ts: the logo (web/public/icon.svg, mark.svg) and the Android
// launcher vectors (adaptive foreground, monochrome silhouette). Run from web/:
// `npm run mascot:assets`; then `npm run site:mascot` for the site and
// `python scripts/mascot_png.py` (repo root) for the PNGs.
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, "..");
const root = resolve(web, "..");

const result = await build({
  entryPoints: [resolve(web, "src/components/redPandaShapes.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  write: false,
  logLevel: "warning",
});
const require = createRequire(import.meta.url);
const m = { exports: {} };
new Function("module", "exports", "require", result.outputFiles[0].text)(m, m.exports, require);
const { flatHead, monochromeHead, HEAD_BOX, PALETTE } = m.exports;

const shapes = flatHead();
const paths = (indent, attr) => shapes.map((s) => `${indent}<path d="${s.d}" fill="${s.fill}"${attr ?? ""}/>`).join("\n");

// The head with its ears is 148×138 in the 200 box, centred on (100, 97). Each target scales
// that box to fit its own safe area.
const fit = (side, fraction) => {
  const s = (side * fraction) / Math.max(HEAD_BOX.width, HEAD_BOX.height);
  const cx = HEAD_BOX.x + HEAD_BOX.width / 2;
  const cy = HEAD_BOX.y + HEAD_BOX.height / 2;
  return { s, tx: side / 2 - cx * s, ty: side / 2 - cy * s };
};
const f2 = (n) => Number(n.toFixed(2));

// mark.svg — the head alone, transparent, filling its box (the same transform as detail="mark")
{
  const { s, tx, ty } = fit(200, 0.92);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <!-- generated by web/scripts/mascot-assets.mjs from redPandaShapes.ts — do not edit -->
  <g transform="translate(${f2(tx)} ${f2(ty)}) scale(${f2(s)})">
${paths("    ")}
  </g>
</svg>
`;
  writeFileSync(resolve(web, "public/mark.svg"), svg);
}

// icon.svg — the head on the forest-green plate, for the PWA and the favicon
{
  const { s, tx, ty } = fit(512, 0.7);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- generated by web/scripts/mascot-assets.mjs from redPandaShapes.ts — do not edit -->
  <rect width="512" height="512" rx="112" fill="${PALETTE.logoPlate}"/>
  <g transform="translate(${f2(tx)} ${f2(ty)}) scale(${f2(s)})">
${paths("    ")}
  </g>
</svg>
`;
  writeFileSync(resolve(web, "public/icon.svg"), svg);
}

// Android adaptive icon: a 108 dp canvas whose inner 66 dp are guaranteed visible.
const argb = (hex) => `#FF${hex.slice(1).toUpperCase()}`;
const android = resolve(root, "android/app/src/main/res/drawable");
{
  const { s, tx, ty } = fit(108, 0.56);
  const body = shapes
    .map(
      (sh) => `        <path
            android:pathData="${sh.d}"
            android:fillColor="${argb(sh.fill)}" />`,
    )
    .join("\n");
  const xml = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- the red panda's head, generated by web/scripts/mascot-assets.mjs from redPandaShapes.ts; do not edit -->
    <group
        android:scaleX="${f2(s)}"
        android:scaleY="${f2(s)}"
        android:translateX="${f2(tx)}"
        android:translateY="${f2(ty)}">
${body}
    </group>
</vector>
`;
  writeFileSync(resolve(android, "ic_launcher_foreground.xml"), xml);

  const mono = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- the red panda's silhouette for themed icons, generated by web/scripts/mascot-assets.mjs; do not edit -->
    <group
        android:scaleX="${f2(s)}"
        android:scaleY="${f2(s)}"
        android:translateX="${f2(tx)}"
        android:translateY="${f2(ty)}">
        <path
            android:pathData="${monochromeHead()}"
            android:fillColor="#FFFFFFFF"
            android:fillType="nonZero" />
    </group>
</vector>
`;
  writeFileSync(resolve(android, "ic_launcher_monochrome.xml"), mono);
}

// The simulated phone's launcher icon (MobileGym): the same head as a React component.
{
  const { s, tx, ty } = fit(48, 0.94);
  const tsx = `// The red panda's head as the launcher icon of the simulated phone. Generated by
// web/scripts/mascot-assets.mjs from web/src/components/redPandaShapes.ts — do not edit.
// It takes the props the launcher passes a lucide icon and keeps its own colours.
export function NanoMuseMark({ size = 48, className, style }: { size?: number | string; color?: string; strokeWidth?: number | string; className?: string; style?: React.CSSProperties }) {
  return (
    <svg viewBox="0 0 48 48" width={size} height={size} className={className} style={style} aria-hidden="true">
      <g transform="translate(${f2(tx)} ${f2(ty)}) scale(${f2(s)})">
${shapes.map((sh) => `        <path d="${sh.d}" fill="${sh.fill}" />`).join("\n")}
      </g>
    </svg>
  );
}
`;
  writeFileSync(resolve(root, "demo/mobilegym/apps/nanoMuse/res/mark.tsx"), tsx);
}

console.log("wrote web/public/{icon,mark}.svg, android ic_launcher_{foreground,monochrome}.xml, demo/mobilegym/.../res/mark.tsx");
