// Renders the red panda (web/src/components/RedPanda.tsx) once per mood to static SVG and
// writes it, with its stylesheet, into site/assets — so the landing page shows the very same
// mascot as the app without shipping React. Run from web/: `npm run site:mascot`.
import { build } from "esbuild";
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, "..");
const out = resolve(web, "..", "site", "assets");
mkdirSync(out, { recursive: true });

const entry = `
  import React from "react";
  import { renderToStaticMarkup } from "react-dom/server";
  import { RedPanda } from "${resolve(web, "src/components/RedPanda.tsx")}";
  const moods = ["idle", "working", "waiting", "happy", "sleepy", "error"];
  const svgs = {};
  for (const m of moods) svgs[m] = renderToStaticMarkup(React.createElement(RedPanda, { mood: m, size: 200, bg: "none" }));
  module.exports = svgs;
`;
const result = await build({
  stdin: { contents: entry, resolveDir: web, loader: "ts" },
  bundle: true,
  platform: "node",
  format: "cjs",
  jsx: "automatic",
  loader: { ".css": "empty" },
  write: false,
  logLevel: "warning",
});
const require = createRequire(import.meta.url);
const m = { exports: {} };
new Function("module", "exports", "require", result.outputFiles[0].text)(m, m.exports, require);
const svgs = m.exports;

writeFileSync(
  resolve(out, "mascot.js"),
  `// generated by web/scripts/site-mascot.mjs — do not edit\nwindow.NANOMUSE_MASCOT = ${JSON.stringify(svgs)};\n`,
);
copyFileSync(resolve(web, "src/components/RedPanda.css"), resolve(out, "mascot.css"));
copyFileSync(resolve(web, "public/icon.svg"), resolve(out, "icon.svg"));
copyFileSync(resolve(web, "public/mark.svg"), resolve(out, "mark.svg"));
mkdirSync(resolve(out, "fonts"), { recursive: true });
for (const f of ["figtree-latin.woff2", "figtree-latin-ext.woff2", "OFL.txt"]) {
  copyFileSync(resolve(web, "public/fonts", f), resolve(out, "fonts", f));
}
// The app screenshots and the cover live in docs/ (the README uses them); the page gets a copy.
const docs = resolve(web, "..", "docs");
mkdirSync(resolve(out, "screens"), { recursive: true });
for (const f of readdirSync(resolve(docs, "screenshots")).filter((f) => f.endsWith(".png"))) {
  copyFileSync(resolve(docs, "screenshots", f), resolve(out, "screens", f));
}
copyFileSync(resolve(docs, "cover.png"), resolve(out, "cover.png"));
console.log(
  `site/assets: mascot.js (${Object.keys(svgs).length} moods), mascot.css, icon.svg, mark.svg, cover.png, fonts/, screens/`,
);
